### PR TITLE
Adding exoneration to TE, NC and ND

### PR DESCRIPTION
**Pull request by PlainGreed**
Description of the issue/feature this PR addresses:

Current behavior before PR:

Desired behavior after PR is merged:

### CODE REVIEW

**Review by charlit02390 — APPROVED** [review]
Se ven bien mae!

**Comment by EstebanMonge** [comment]
Se ve bien

**Review by EstebanMonge — APPROVED** [review]
se ve bien

**Review by EstebanMonge — APPROVED** [review]
se ve bien

**Review by EstebanMonge — APPROVED** [review]
Aprobado

**Pull request merged**
